### ISSUE TITLE
markers removed when typing

### ISSUE THREAD

**Issue by danielnaber** [seleznevStas/TextEditorHighlighter#3]
When there are markers and I typo more text, the markers disappear. Can this be improved?

**Comment by seleznevStas** [comment]
Implemented with #7ed7dfe1882c90f6840c91ec4a87f80f708d9cdb

**Comment by danielnaber** [comment]
Thanks - if you mention the issue number in the commit message, like `#3`, github will automatically link issues and commits, BTW. That's easier than pasting the commit hash here.
